[package]
name = "fuel-zkvm-primitives-test-fixtures"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
fuel-core = { version = "0.40.0", features = [
  "rocksdb",
  "wasm-executor",
  "relayer",
  "test-helpers",
] }
fuel-core-executor = { workspace = true }
fuel-core-storage = { workspace = true }
fuel-core-types = { workspace = true }
fuels = "0.66.10"
fuels-core = "0.66.10"
fuel-zkvm-primitives-input-provider = { path = "../fuel-zkvm-primitives-input-provider" }
fuel-zkvm-primitives-prover = { path = "../fuel-zkvm-primitives-prover" }
fuel-zkvm-primitives-utils = { path = "../fuel-zkvm-primitives-utils" }
serde_json = { version = "1", default-features = false }
tempfile = "3.14.0"
tokio = { workspace = true }
clap = { version = "^4.0", features = ["derive"], optional = true }
enum-iterator = { version = "2.1.0", optional = true }

[dev-dependencies]
paste = "1.0"

[features]
enhanced_enums = ["fuel-zkvm-primitives-utils/enhanced_enums", "enum-iterator", "clap"]