name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - name: Install forc
      run: |
        curl https://install.fuel.network | sh
        export PATH="${HOME}/.fuelup/bin:${PATH}"
    - name: Build
      run: cargo build --verbose --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        rustup target add wasm32-unknown-unknown
        rustup toolchain install nightly
        rustup component add rustfmt --toolchain nightly
    - name: Install forc
      run: |
        curl https://install.fuel.network | sh
        export PATH="${HOME}/.fuelup/bin:${PATH}"
    - uses: Swatinem/rust-cache@v2
    - name: Clippy
      run: cargo clippy --all --all-features
    - name: Formatting
      run: cargo +nightly fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Install forc
      run: |
        curl https://install.fuel.network | sh
        export PATH="${HOME}/.fuelup/bin:${PATH}"
    - uses: actions/checkout@v4
    - run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
    - name: Run tests
      run: cargo nextest run