name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --all --all-features
    - name: Formatting
      run: cargo +nightly fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo nextest run